version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-app
    container_name: vue-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
